namespace InsuranceIntegration.Api.Services.Catalog;

public sealed class SourceSystemCatalogService : ISourceSystemCatalogService
{
    public IReadOnlyCollection<SourceSystemCatalogItem> GetSourceSystems()
    {
        return
        [
            new() { SystemCode = "POLARIS_UW", DisplayName = "Polaris Underwriting Workbench", BusinessPurpose = "Risk intake and underwriting submissions", MessageType = "RiskSubmission", ExamplePayload = new { quoteId = "Q-100045", insuredName = "Northwind Storage Ltd", trade = "CommercialProperty", estimatedPremium = 12500.00m } },
            new() { SystemCode = "QUOTEFORGE", DisplayName = "QuoteForge Quote Engine", BusinessPurpose = "Quote generation and pricing requests", MessageType = "QuoteRequest", ExamplePayload = new { quoteReference = "QT-2001", insuredName = "Harborline Services", productLine = "Liability", brokerCode = "BRK-44", brokerName = "Summit Risk Partners", technicalPremium = 8200.00m, brokerPremium = 8500.00m, currencyCode = "USD", effectiveDate = "2026-05-01", expiryDate = "2027-04-30", underwritingYear = 2026, insuredRevenue = 1500000.00m, insuredEmployeeCount = 25, insuredYearsInBusiness = 8 } },
            new() { SystemCode = "BINDPOINT", DisplayName = "BindPoint Policy Bind Service", BusinessPurpose = "Policy bind and issuance events", MessageType = "PolicyBindRequest", ExamplePayload = new { policyReference = "POL-7781", quoteReference = "QT-2001", insuredName = "Harborline Services", productCode = "LIABILITY", brokerCode = "BRK-44", brokerName = "Summit Risk Partners", brokerHasDelegatedAuthority = false, brokerIsPreferredPartner = true, boundPremium = 8500.00m, currencyCode = "USD", inceptionDate = "2026-05-01", expiryDate = "2027-04-30", boundDate = "2026-04-28", paymentMethod = "Invoice", installmentCount = 4 } },
            new() { SystemCode = "POLICYCORE", DisplayName = "PolicyCore Policy Master", BusinessPurpose = "Policy master records and issuance notifications", MessageType = "PolicyIssued", ExamplePayload = new { policyReference = "POL-7782", insuredName = "Northwind Storage Ltd", productCode = "COMMERCIAL_PROPERTY", inceptionDate = "2026-06-01", expiryDate = "2027-05-31", annualPremium = 14500.00m } },
            new() { SystemCode = "RENEWALPILOT", DisplayName = "RenewalPilot Renewal Orchestrator", BusinessPurpose = "Policy renewal notices and renewal quote intents", MessageType = "RenewalNotice", ExamplePayload = new { policyReference = "POL-7781", renewalQuoteReference = "QT-2101", renewalEffectiveDate = "2027-05-01", previousPremium = 8500.00m, indicativeRenewalPremium = 8900.00m } },
            new() { SystemCode = "CLAIMFORGE", DisplayName = "ClaimForge Claim Hub", BusinessPurpose = "Claims notification and updates", MessageType = "ClaimNotice", ExamplePayload = new { claimReference = "CLM-9001", claimantName = "Avery Cole", lossDate = "2026-01-12", estimatedIncurred = 3400.50m } },
            new() { SystemCode = "BROKERHUB", DisplayName = "BrokerHub Exchange", BusinessPurpose = "Broker-originated placement traffic", MessageType = "Submission", ExamplePayload = new { brokerCode = "BRK-44", insuredName = "Harborline Services", product = "Liability", technicalPremium = 8200.00m } },
            new() { SystemCode = "SANCTIONSCAN", DisplayName = "SanctionScan Screening", BusinessPurpose = "Compliance screening results", MessageType = "ComplianceResult", ExamplePayload = new { partyName = "Northwind Storage Ltd", screeningResult = "Clear", score = 0 } },
            new() { SystemCode = "PAYMENTRAIL", DisplayName = "PaymentRail Billing Gateway", BusinessPurpose = "Installment and payment events", MessageType = "InstallmentSchedule", ExamplePayload = new { policyReference = "POL-7781", installmentCount = 4, totalAmount = 12000.00m } },
            new() { SystemCode = "REINS_LINK", DisplayName = "Reins Link Placement", BusinessPurpose = "Reinsurance cession and placement advice", MessageType = "PlacementAdvice", ExamplePayload = new { treatyCode = "TRT-22", cededShare = 0.25m, riskReference = "RISK-108" } },
            new() { SystemCode = "FRAUDLENS", DisplayName = "FraudLens Insight", BusinessPurpose = "Fraud scoring and triage", MessageType = "FraudAssessment", ExamplePayload = new { entityReference = "ENT-55", fraudScore = 12, recommendation = "Monitor" } },
            new() { SystemCode = "DOCVAULT", DisplayName = "DocVault Repository", BusinessPurpose = "Document registration and retrieval", MessageType = "DocumentRegistered", ExamplePayload = new { documentId = "DOC-1001", category = "ProposalForm", entityReference = "ENT-55" } },
            new() { SystemCode = "ENDORSE_PRO", DisplayName = "EndorsePro Change Manager", BusinessPurpose = "Mid-term adjustments and endorsements", MessageType = "EndorsementRequest", ExamplePayload = new { policyReference = "POL-7781", changeType = "AddSection", sectionCode = "PROP" } },
            new() { SystemCode = "LOSSWATCH", DisplayName = "LossWatch Monitor", BusinessPurpose = "Loss run summaries and alerts", MessageType = "LossRun", ExamplePayload = new { insuredName = "Northwind Storage Ltd", claimCount = 3, totalIncurred = 15600.00m } }
        ];
    }
}
